### ISSUE TITLE
missing dep error when following README

### ISSUE THREAD

**Issue by bmabey** [juxt/qcon2014#1]
I followed the `README` but when I run `lein repl` from the `jig` directory I get:

```
ArtifactNotFoundException: Could not find artifact jig:protocols:jar:qcon
```

I tried doing a `lein install` in the `qcon` project but that didn't help.  Any ideas what the missing step would be to install the needed dep?

**Comment by malcolmsparks** [comment]
Sorry, my fault, you need to delete the qcon tag and try again. I've
removed it from the remote repo.

$ cd jig
$ git tag -d qcon
$ lein repl

Let me know if that works.

**Comment by bmabey** [comment]
That helped.  I then ran into:

```
#<Exception java.lang.Exception: Error loading /Users/.../om-slides-example/qcon/project.clj>
```

Renaming `qcon2014` to `qcon` fixed that.

Thanks!
