### ISSUE TITLE
put and take examples not working

### ISSUE THREAD

**Issue by bmabey** [juxt/qcon2014#3]
I'm sure this is an environment issue but I can't get the put and take examples to work.  This video recording will make the most sense:
http://screencast.com/t/KDxvzYjC

When I push the button that is suppose to put vals on to the chan several numbers flash in the box but they never make it to the channel circles nor does 
the take work.

Any idea what is going on here?  I've tried Chrome, FF, and Safari and none of them work.  I haven't dived into the code yet since I thought you may have a better idea.

Is there any chance you could put the slide deck back up at http://qcon.juxt.pro/index.html (as advertised in the README)?  If you do I can see if your built version works for me and that would help narrow down the issue. Right now when I go to that URL I get a login page.

**Comment by malcolmsparks** [comment]
Hi Ben,

Thanks for the video - that stopped me from sending you down the wrong
path. It's not intuitive, but you're meant to click on the symbols
themselves (>! and <!) Click on the >! after you've generated a number.

Let me know how you get on.

Regards,

Malcolm

**Comment by bmabey** [comment]
Ah, sorry for the noise.  It works great.

**Comment by malcolmsparks** [comment]
No problem Ben, nice to hear from you. In your defense, I didn't consider
the chance others might be driving this deck, so it's not very intuitive.
